[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "image/png"

[[headers]]
  for = "/typeinbanner.png"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "image/png" 